# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/designSDK/designSDK.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==designSDK || ORIG_REF_NAME==designSDK} -quiet] -quiet

# IP: bd/designSDK/ip/designSDK_processing_system7_0_0/designSDK_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==designSDK_processing_system7_0_0 || ORIG_REF_NAME==designSDK_processing_system7_0_0} -quiet] -quiet

# IP: bd/designSDK/ip/designSDK_axi_gpio_0_0/designSDK_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==designSDK_axi_gpio_0_0 || ORIG_REF_NAME==designSDK_axi_gpio_0_0} -quiet] -quiet

# IP: bd/designSDK/ip/designSDK_auto_pc_0/designSDK_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==designSDK_auto_pc_0 || ORIG_REF_NAME==designSDK_auto_pc_0} -quiet] -quiet

# IP: bd/designSDK/ip/designSDK_ps7_0_axi_periph_0/designSDK_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==designSDK_ps7_0_axi_periph_0 || ORIG_REF_NAME==designSDK_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/designSDK/ip/designSDK_rst_ps7_0_50M_0/designSDK_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==designSDK_rst_ps7_0_50M_0 || ORIG_REF_NAME==designSDK_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/designSDK/designSDK_ooc.xdc
