webtalk_init -webtalk_dir C:/Users/m_rah/Desktop/Co-design/deocder2to4 with en and when en is absand/deocder2to4 with en and when en is absand.sim/sim_1/behav/xsim/xsim.dir/dec2to4_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Aug 18 21:07:22 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3dae56c8-39cb-4189-95ae-7663a03200e4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "183650f10cc444d48b6513e955a8680c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "71" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6344_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3412179012 -regid "" -xml C:/Users/m_rah/Desktop/Co-design/deocder2to4 with en and when en is absand/deocder2to4 with en and when en is absand.sim/sim_1/behav/xsim/xsim.dir/dec2to4_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/m_rah/Desktop/Co-design/deocder2to4 with en and when en is absand/deocder2to4 with en and when en is absand.sim/sim_1/behav/xsim/xsim.dir/dec2to4_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/m_rah/Desktop/Co-design/deocder2to4 with en and when en is absand/deocder2to4 with en and when en is absand.sim/sim_1/behav/xsim/xsim.dir/dec2to4_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
